name: openai
channels:
  - bioconda
  - anaconda
  - conda-forge
  - rwest
  - vgauthier
  - defaults
dependencies:
  - anyio=3.6.2=pyhd8ed1ab_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39ha30fb19_3
  - asttokens=2.2.1=pyhd8ed1ab_0
  - atk-1.0=2.36.0=he69c4ee_4
  - attrs=22.2.0=pyh71513ae_0
  - babel=2.11.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.2=pyha770c72_0
  - bleach=6.0.0=pyhd8ed1ab_0
  - boost=1.74.0=py39ha1f3e3e_5
  - boost-cpp=1.74.0=hff03dee_4
  - brotlipy=0.7.0=py39h9ed2024_1003
  - bzip2=1.0.8=h0d85af4_4
  - ca-certificates=2022.4.26=hecd8cb5_0
  - cairo=1.16.0=he43a7df_1008
  - cairomm=1.12.2=h694c41f_4
  - cairomm-1.0=1.12.2=h6e63b80_3
  - certifi=2022.6.15=py39hecd8cb5_0
  - cffi=1.15.0=py39hc55c11b_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - chkconfig-cos7-s390x=1.7.4=2
  - conda-content-trust=0.1.1=pyhd3eb1b0_0
  - conda-package-handling=1.8.1=py39hca72f7f_0
  - cryptography=36.0.0=py39hf6deb26_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - epoxy=1.5.10=h5eb16cf_1
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hf0c8a7f_1
  - flit-core=3.8.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.94=h10f422b_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h3f81eb7_0
  - fribidi=1.0.10=hbcb3906_0
  - g-ir-build-tools=1.68.0=py39h503e71d_2
  - g-ir-host-tools=1.68.0=h7115f9e_2
  - gdk-pixbuf=2.42.6=h2e6141f_0
  - gettext=0.21.1=h8a4c099_0
  - glib-tools=2.68.4=he49afe7_0
  - gmp=6.2.1=h2e338ed_0
  - gobject-introspection=1.68.0=py39h1652fd0_2
  - graph-tool=2.43=py39h56aae46_0
  - graph-tool-base=2.43=py39h40ae025_0
  - graphite2=1.3.13=h2e338ed_1001
  - gtk3=3.24.29=he55cb93_3
  - harfbuzz=3.0.0=h159f659_1
  - hicolor-icon-theme=0.17=h694c41f_2
  - icu=68.2=he49afe7_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib_resources=5.10.2=pyhd8ed1ab_0
  - ipykernel=5.5.5=py39h71a6800_0
  - ipython=8.9.0=pyhd1c38e8_0
  - ipython_genutils=0.2.0=py_1
  - java-1.8.0-openjdk-devel-cos7-s390x=1.8.0.242.b08=2
  - java-jdk=7.0.91=1
  - jbig=2.1=h0d85af4_2003
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=hb7f2c08_3
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_client=7.0.6=pyhd8ed1ab_0
  - jupyter_core=5.2.0=py39h6e9494a_0
  - jupyter_server=1.23.5=pyhd8ed1ab_0
  - jupyterlab=3.5.3=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.10.3=pyhd3eb1b0_1
  - lerc=3.0=he49afe7_0
  - libblas=3.9.0=17_osx64_openblas
  - libcblas=3.9.0=17_osx64_openblas
  - libcxx=12.0.0=h2f01273_0
  - libdeflate=1.10=h0d85af4_0
  - libexpat=2.5.0=hf0c8a7f_1
  - libffi=3.3=hb1e8313_2
  - libgfortran=5.0.0=12_3_0_h97931a8_1
  - libgfortran5=12.3.0=hbd3c1fe_1
  - libgirepository=1.68.0=h992b352_2
  - libglib=2.68.4=hd556434_0
  - libiconv=1.17=hac89ed1_0
  - liblapack=3.9.0=17_osx64_openblas
  - libopenblas=0.3.23=openmp_h429af6e_0
  - libpng=1.6.38=ha978bb4_0
  - librsvg=2.52.2=h02b643e_0
  - libsodium=1.0.18=hbcb3906_1
  - libtiff=4.3.0=h17f2ce3_3
  - libwebp-base=1.3.1=h0dc2134_0
  - libxml2=2.9.12=h93ec3fd_0
  - libzlib=1.2.12=hfe4f2af_1
  - llvm-openmp=16.0.6=hff08bdf_0
  - lz4-c=1.9.3=he49afe7_1
  - matchtigs=1.2.0=hdfd78af_0
  - matplotlib-base=2.2.5=py39he2de7ed_3
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=2.0.4=pyhd8ed1ab_0
  - nbclassic=0.5.1=pyhd8ed1ab_0
  - nbclient=0.7.2=pyhd8ed1ab_0
  - nbconvert=7.2.9=pyhd8ed1ab_0
  - nbconvert-core=7.2.9=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.9=pyhd8ed1ab_0
  - nbformat=5.7.3=pyhd8ed1ab_0
  - ncurses=6.3=hca72f7f_2
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - notebook=6.5.2=pyha770c72_1
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - openjdk=8.0.152=h1de35cc_3
  - openssl=1.1.1o=hca72f7f_0
  - pandoc=2.19.2=h694c41f_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.48.10=h056538c_2
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=he49afe7_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=21.2.4=py39hecd8cb5_0
  - pixman=0.40.0=hbcb3906_0
  - pkg-config=0.29.2=ha3d46e9_1008
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - prometheus_client=0.16.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.36=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycairo=1.24.0=py39h48b375e_0
  - pycosat=0.6.3=py39h9ed2024_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pygobject=3.40.1=py39h8819ad7_1
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyrsistent=0.19.3=py39ha30fb19_0
  - pysocks=1.7.1=py39hecd8cb5_0
  - python=3.9.12=hdfd78df_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python.app=3=py39hca72f7f_0
  - python_abi=3.9=2_cp39
  - pytz=2022.7.1=pyhd8ed1ab_0
  - pyzmq=19.0.2=py39he75b00d_2
  - readline=8.1.2=hca72f7f_1
  - ruamel.yaml=0.17.21=py39ha30fb19_2
  - ruamel.yaml.clib=0.2.7=py39ha30fb19_1
  - ruamel_yaml=0.15.100=py39h9ed2024_0
  - rust=1.62.0=h7e1429e_0
  - rust-std-x86_64-apple-darwin=1.62.0=h059895a_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=61.2.0=py39hecd8cb5_0
  - sigcpp-2.0=2.10.7=he49afe7_1
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sparsehash=2.0.4=he49afe7_0
  - sqlite=3.38.2=h707629a_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - terminado=0.17.1=pyhd1c38e8_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.11=h7bc2e8c_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.2=py39ha30fb19_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.5.0=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - yaml=0.2.5=haf1e3a3_0
  - zeromq=4.3.4=he49afe7_1
  - zipp=3.12.0=pyhd8ed1ab_0
  - zlib=1.2.12=h4dc903c_1
  - zstandard=0.19.0=py39h5705987_2
  - zstd=1.5.2=h582d3a0_0
  - pip:
      - absl-py==2.0.0
      - aiofiles==23.1.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - alabaster==0.7.13
      - altair==5.1.1
      - ansiterm==1.1
      - appdirs==1.4.4
      - arrow==1.2.3
      - astroid==2.5
      - astunparse==1.6.3
      - async-timeout==4.0.2
      - asyncer==0.0.2
      - asyncio==3.4.3
      - auth0-python==4.3.0
      - automat==22.10.0
      - backoff==2.2.1
      - bel-resources==0.0.3
      - bert-score==0.3.13
      - bibtexparser==1.4.0
      - bidict==0.22.1
      - bio==1.5.9
      - biopython==1.80
      - bioregistry==0.10.38
      - biothings-client==0.3.0
      - black==23.3.0
      - bleurt==0.0.2
      - blinker==1.6.2
      - boto3==1.28.49
      - botocore==1.31.49
      - bs4==0.0.1
      - cachetools==5.3.1
      - cattrs==23.1.2
      - cfgv==3.3.1
      - chainlit==0.5.2
      - chardet==5.1.0
      - ci-info==0.3.0
      - click==8.1.6
      - click-plugins==1.1.1
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - configobj==5.0.8
      - configparser==6.0.0
      - constantly==15.1.0
      - contourpy==1.1.0
      - coverage==7.2.7
      - crossref-commons==0.0.7
      - cssselect==1.2.0
      - curies==0.6.2
      - dataclasses-json==0.5.7
      - datasets==2.14.5
      - deprecated==1.2.14
      - deprecation==2.0.7
      - dill==0.3.7
      - distlib==0.3.6
      - dnspython==2.4.2
      - docopt==0.6.2
      - docutils==0.18.1
      - enum34==1.1.10
      - etelemetry==0.3.0
      - eutils==0.6.0
      - evaluate==0.4.0
      - exceptiongroup==1.1.2
      - faiss-cpu==1.7.4
      - fake-useragent==1.1.3
      - fastapi==0.96.0
      - fastapi-socketio==0.0.10
      - filelock==3.12.2
      - filetype==1.2.0
      - fitz==0.0.1.dev2
      - flatbuffers==23.5.26
      - fonttools==4.40.0
      - free-proxy==1.1.1
      - frozenlist==1.3.3
      - fsspec==2023.6.0
      - future==0.18.3
      - gast==0.4.0
      - gensim==4.3.1
      - gitdb==4.0.10
      - gitpython==3.1.36
      - google-auth==2.23.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.59.1
      - gprofiler-official==1.0.0
      - gpt-engineer==0.0.7
      - graph-tools==1.11
      - greenlet==2.0.2
      - grpcio==1.56.2
      - h11==0.14.0
      - h5py==3.9.0
      - habanero==1.2.3
      - htmlparser==0.0.2
      - httpcore==0.17.3
      - httplib2==0.22.0
      - httpx==0.24.1
      - huggingface-hub==0.16.4
      - humanfriendly==10.0
      - humanize==4.8.0
      - hyperlink==21.0.0
      - identify==2.5.24
      - idna==2.10
      - ijson==3.2.3
      - imagesize==1.4.1
      - incremental==22.10.0
      - indra==1.22.0
      - iniconfig==2.0.0
      - interchange==2021.0.4
      - ipython-autotime==0.3.1
      - isodate==0.6.1
      - isort==5.12.0
      - itemadapter==0.7.0
      - itemloaders==1.0.6
      - jmespath==1.0.1
      - joblib==1.3.1
      - jsonlines==4.0.0
      - keras==2.13.1
      - kiwisolver==1.4.4
      - langchain==0.0.284
      - langchainplus-sdk==0.0.17
      - langsmith==0.0.33
      - lark==1.1.7
      - lazy-object-proxy==1.9.0
      - levenshtein==0.21.1
      - libclang==16.0.6
      - loguru==0.7.1
      - looseversion==1.3.0
      - lxml==4.9.2
      - markdown==3.4.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - marshmallow==3.19.0
      - marshmallow-enum==1.5.1
      - matplotlib==3.7.2
      - mbstrdecoder==1.1.3
      - mccabe==0.6.1
      - mdurl==0.1.2
      - metapub==0.5.5
      - monotonic==1.6
      - more-click==0.1.2
      - more-itertools==10.1.0
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.15
      - multisplitby==0.0.1
      - mygene==3.2.2
      - mypy==1.3.0
      - mypy-extensions==1.0.0
      - ndex2==2.0.1
      - neo4j==5.12.0
      - networkx==3.1
      - nibabel==5.1.0
      - nipype==1.8.6
      - nltk==3.8.1
      - nodeenv==1.8.0
      - numexpr==2.8.4
      - numpy==1.24.1
      - oauthlib==3.2.2
      - objectpath==0.6.1
      - obonet==1.0.0
      - openai==0.27.8
      - openapi-schema-pydantic==1.2.4
      - opentelemetry-api==1.18.0
      - opentelemetry-exporter-otlp==1.18.0
      - opentelemetry-exporter-otlp-proto-common==1.18.0
      - opentelemetry-exporter-otlp-proto-grpc==1.18.0
      - opentelemetry-exporter-otlp-proto-http==1.18.0
      - opentelemetry-instrumentation==0.39b0
      - opentelemetry-proto==1.18.0
      - opentelemetry-sdk==1.18.0
      - opentelemetry-semantic-conventions==0.39b0
      - opt-einsum==3.3.0
      - outcome==1.2.0
      - packaging==23.1
      - pandas==1.3.0
      - pansi==2020.7.3
      - parse==1.19.1
      - parsel==1.7.0
      - pathlib==1.0.1
      - pathspec==0.11.1
      - pax2graphml==1.1.3
      - pdfminer-six==20221105
      - pdfplumber==0.9.0
      - perlcompat==1.1
      - pillow==9.5.0
      - pinecone-client==2.2.2
      - platformdirs==3.8.1
      - pluggy==1.2.0
      - pooch==1.7.0
      - pre-commit==3.3.3
      - prisma==0.9.1
      - protego==0.2.1
      - protmapper==0.0.28
      - protobuf==4.23.4
      - prov==2.0.0
      - psycopg2-binary==2.9.7
      - pubmed-parser==0.3.1
      - pubmed2pdf==0.0.3
      - py2neo==2021.2.3
      - pyarrow==13.0.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pybel==0.15.5
      - pybiomart==0.2.0
      - pybiopax==0.1.4
      - pychainedproxy==1.2
      - pydantic==1.10.9
      - pydeck==0.8.0
      - pydispatcher==2.0.6
      - pydot==1.4.2
      - pyee==8.2.2
      - pyjwt==2.8.0
      - pylint==2.7.1
      - pympler==1.0.1
      - pymupdf==1.23.3
      - pymupdfb==1.23.3
      - pypaperbot==1.2.2
      - pyparsing==3.0.9
      - pypdf==3.15.5
      - pypdf2==3.0.1
      - pyppeteer==1.0.2
      - pyproject-api==1.5.3
      - pyquery==2.0.0
      - pysb==1.15.0
      - pysbd==0.3.4
      - pysolr==3.9.0
      - pystow==0.5.0
      - pytess==1.0.0
      - pytest==7.3.1
      - pytest-cov==4.1.0
      - python-dotenv==1.0.0
      - python-engineio==4.5.1
      - python-graphql-client==0.4.3
      - python-levenshtein==0.21.1
      - python-socketio==5.8.0
      - pytrie==0.4.0
      - pytz-deprecation-shim==0.1.0.post0
      - pyxnat==1.6
      - pyyaml==6.0
      - queuelib==1.6.2
      - rapidfuzz==3.1.1
      - ratelimit==2.2.1
      - rdflib==7.0.0
      - regex==2023.6.3
      - requests==2.31.0
      - requests-cache==1.1.0
      - requests-file==1.5.1
      - requests-html==0.10.0
      - requests-oauthlib==1.3.1
      - requests-toolbelt==1.0.0
      - requests3==0.0.0
      - requestsexceptions==1.4.0
      - responses==0.18.0
      - rich==13.5.2
      - rouge==1.0.1
      - rouge-score==0.1.2
      - rsa==4.9
      - rudder-sdk-python==2.0.2
      - ruff==0.0.272
      - s3transfer==0.6.2
      - safetensors==0.3.1
      - scholarly==1.7.11
      - scikit-learn==1.3.0
      - scipy==1.11.1
      - scraper==0.1.0
      - scrapy==2.7.1
      - selenium==4.10.0
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - service-identity==21.1.0
      - simplejson==3.19.1
      - smart-open==6.3.0
      - smmap==5.0.0
      - snowballstemmer==2.2.0
      - sortedcontainers==2.4.0
      - sphinx==7.2.6
      - sphinx-rtd-theme==1.3.0
      - sphinxcontrib-applehelp==1.0.7
      - sphinxcontrib-devhelp==1.0.5
      - sphinxcontrib-htmlhelp==2.0.4
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.6
      - sphinxcontrib-serializinghtml==1.1.9
      - sqlalchemy==2.0.17
      - starlette==0.27.0
      - streamlit==1.26.0
      - subprocrunner==2.0.0
      - sympy==1.12
      - syncer==2.0.3
      - tabulate==0.9.0
      - tbdump==1.4
      - tenacity==8.2.2
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.1
      - tensorflow==2.13.0
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.3.0
      - tf-slim==1.1.0
      - threadpoolctl==3.2.0
      - tiktoken==0.4.0
      - tldextract==3.4.0
      - tokenizers==0.13.3
      - toml==0.10.2
      - tomlkit==0.11.8
      - torch==2.0.1
      - torchvision==0.15.2
      - tox==4.6.4
      - tqdm==4.66.1
      - traits==6.3.2
      - transformers==4.31.0
      - trio==0.22.2
      - trio-websocket==0.10.3
      - twisted==22.10.0
      - typer==0.9.0
      - typing-inspect==0.9.0
      - tzdata==2023.3
      - tzlocal==4.3.1
      - unidecode==1.3.6
      - uptrace==1.18.0
      - url-normalize==1.4.3
      - urllib3==1.26.16
      - uvicorn==0.22.0
      - validators==0.22.0
      - virtualenv==20.23.1
      - w3lib==2.1.1
      - wand==0.6.11
      - watchfiles==0.19.0
      - websockets==10.4
      - werkzeug==2.3.7
      - wget==3.2
      - wrapt==1.12.1
      - wsproto==1.2.0
      - xmltodict==0.13.0
      - xxhash==3.3.0
      - yarl==1.9.2
      - zope-interface==5.5.2
prefix: /Users/falmodaresi/miniconda3/envs/openai
